version: '3.7'

networks:
  py-app:
    driver: bridge
    ipam:
      config:
        - subnet: 10.11.12.0/29
volumes:
  dbdata:


services:
  db:
    image: mysql:5.7
    container_name: py_db
    environment:
      MYSQL_DATABASE: book_store
      MYSQL_USER: py
      MYSQL_ROOT_PASSWORD: "$book_store_DB_PASS"
    restart: unless-stopped
    networks:
      py-app:
        ipv4_address: 10.11.12.2
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build:
      context: ../
      dockerfile: ./.mrt/.build
    image: py_app
    container_name: py_app
    restart: unless-stopped
    networks:
      py-app:
        ipv4_address: 10.11.12.3

  pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: py_phpmyadmin
    networks:
      py-app:
        ipv4_address: 10.11.12.4
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "$book_store_DB_PASS"

  webserver:
    image: nginx:alpine
    container_name: py_webserver
    restart: unless-stopped
    volumes:
      - ./ssl/:/etc/ssl/
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/log/:/var/log/nginx/
      - ./webserver/py:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      py-app:
        ipv4_address: 10.11.12.5
